### ISSUE TITLE
 Memory of the discussion chat api

### ISSUE THREAD

**Issue by LinkoLabsBE** [ollama/ollama-js#117]
Hello everyone, I have a question, how can I get them to follow the course of a discussion? I use the "Chat" API but it doesn't work, he doesn't remember the discussion

"Vous: code me a hello world in python
Ollama: Sure, here is a simple "Hello, World!" program in Python for you: ```python print("Hello, World!") ``` When you run this program, it will display "Hello, World!" on your screen. the very first time it's executed.
Vous: What question did I ask previously?
Ollama: ɔƒ ˈsʌən ə ˈpʊqli ə ʃuːl ə ˈbʯrən Asking about previous questions, you asked, "Can you provide me with a definition of plagiarism?""

**Comment by BruceMacD** [comment]
Hi @LinkoLabsBE do you have a code snippet of what you are doing? I looks to me like you probably need to add the previous response to your message history.

Here is an example:
```javascript
import { Ollama, Message } from 'ollama';

(async () => {
    const ollama = new Ollama();

    const msgs: Message[] = [
        { role: "system", content: "you are mario" },
        { role: "user", content: "hello" },
    ];
    const resp1 = await ollama.chat({ model: "llama3", messages: msgs });
    console.log(resp1.message.content);
    msgs.push(resp1.message);

    msgs.push({ role: "user", content: "what is your name?" });

    const resp2 = await ollama.chat({ model: "llama3", messages: msgs });
    console.log(resp2.message.content);
    msgs.push(resp2.message);
})();
```

**Comment by LinkoLabsBE** [comment]
If I understand correctly, I need to create an array that contains the responses and questions to then resend them in the prompt? I am working on PHP because I couldn't find the solution with JS :/ here is my new code:
messenger.php : "<?php
session_start();
if (!isset($_SESSION['username'])) {
    header('Location: login.php');
    exit();
}
$username = $_SESSION['username'];
?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat avec le modèle Renard-V2</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="styles.css">
    <style>
        #loadingAnimation {
            display: none;
            margin-left: 10px;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-light bg-light">
        <a class="navbar-brand" href="#">Renard GPT</a>
        <form class="form-inline">
            <button class="btn btn-secondary theme-toggle" type="button">Changer de Thème</button>
            <a class="btn btn-outline-success my-2 my-sm-0 ml-2" href="logout.php">Déconnexion</a>
        </form>
    </nav>
    <div class="container-fluid mt-4">
        <div class="row">
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        Historique des messages
                    </div>
                    <ul class="list-group list-group-flush" id="messageHistory">
                        
                    </ul>
                </div>
            </div>
            <div class="col-md-9">
                <div class="card">
                    <div class="card-header">
                        Chat avec le modèle Renard-V2
                    </div>
                    <div class="card-body" id="chatOutput">
                        <p>Bienvenue dans le chat !</p>
                    </div>
                    <div class="card-footer">
                        <form id="chatForm">
                            <div class="input-group">
                                <input type="text" id="userMessage" name="message" class="form-control" placeholder="Entrez votre message" required>
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit" id="sendButton">Envoyer</button>
                                    <div id="loadingAnimation" class="spinner-border text-primary" role="status">
                                        <span class="sr-only">Chargement...</span>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        document.getElementById('chatForm').addEventListener('submit', async function(event) {
            event.preventDefault();
            const messageContent = document.getElementById('userMessage').value;
            const loadingAnimation = document.getElementById('loadingAnimation');
            const sendButton = document.getElementById('sendButton');
            const chatOutput = document.getElementById('chatOutput');
            const messageHistory = document.getElementById('messageHistory');
            const username = "<?php echo $username; ?>";

            // Show loading animation and hide send button
            sendButton.style.display = 'none';
            loadingAnimation.style.display = 'inline-block';

            try {
                const response = await fetch('chat.php', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ message: messageContent })
                });

                const result = await response.json();
                chatOutput.innerHTML += `<p><strong>${username}:</strong> ${messageContent}</p>`;
                chatOutput.innerHTML += `<p><strong>Assistant:</strong> ${result.response}</p>`;

                // Add message to history
                const historyItem = document.createElement('li');
                historyItem.className = 'list-group-item';
                historyItem.textContent = `${username}: ${messageContent}`;
                messageHistory.appendChild(historyItem);

                document.getElementById('userMessage').value = '';  // Clear input field

                chatOutput.scrollTop = chatOutput.scrollHeight;  // Scroll to bottom
            } catch (error) {
                console.error('Il y avait un problème avec l\'opération fetch:', error);
                alert('Erreur lors de l\'envoi du message. Veuillez réessayer.');
            } finally {
                // Hide loading animation and show send button
                sendButton.style.display = 'inline-block';
                loadingAnimation.style.display = 'none';
            }
        });

        const themeToggle = document.querySelector('.theme-toggle');
        if (themeToggle) {
            themeToggle.addEventListener('click', function() {
                const bodyClassList = document.body.classList;
                const theme = bodyClassList.contains('bg-light') ? 'dark' : 'light';

                if (theme === 'dark') {
                    bodyClassList.remove('bg-light');
                    bodyClassList.add('bg-dark');
                    bodyClassList.remove('text-dark');
                    bodyClassList.add('text-white');
                } else {
                    bodyClassList.remove('bg-dark');
                    bodyClassList.add('bg-light');
                    bodyClassList.remove('text-white');
                    bodyClassList.add('text-dark');
                }

                const cards = document.querySelectorAll('.card');
                cards.forEach(card => {
                    if (theme === 'dark') {
                        card.classList.add('bg-dark');
                        card.classList.add('text-white');
                    } else {
                        card.classList.remove('bg-dark');
                        card.classList.remove('text-white');
                    }
                });
            });
        }

        // Add animations for better user experience
        const userMessageInput = document.getElementById('userMessage');
        if (userMessageInput) {
            userMessageInput.addEventListener('focus', function() {
                this.classList.add('input-focus');
            });

            userMessageInput.addEventListener('blur', function() {
                this.classList.remove('input-focus');
            });
        }
    </script>
</body>
</html>
"

chat.php : 
"<?php
session_start();
if (!isset($_SESSION['username'])) {
    header('Location: login.php');
    exit();
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $input = json_decode(file_get_contents('php://input'), true);
    $messageContent = $input['message'];

    $data = array(
        "model" => "Renard-V2:latest",
        "messages" => array(
            array(
                "role" => "user",
                "content" => $messageContent
            )
        ),
        "stream" => true
    );

    $options = array(
        'http' => array(
            'header'  => "Content-type: application/json\r\n",
            'method'  => 'POST',
            'content' => json_encode($data),
        ),
    );

    $context  = stream_context_create($options);
    $result = file_get_contents('http://localhost:11434/api/chat', false, $context);

    if ($result === FALSE) {
        echo json_encode(array("response" => "Erreur lors de l'envoi de la requête."));
    } else {
        $fullMessage = '';
        $responseLines = explode("\n", $result);
        foreach ($responseLines as $line) {
            $json = json_decode($line, true);
            if (isset($json['message']) && $json['message']['role'] === 'assistant') {
                $fullMessage .= $json['message']['content'];
            }
        }
        echo json_encode(array("response" => htmlspecialchars($fullMessage, ENT_QUOTES, 'UTF-8')));
    }
}
"
js : 
"// js/scripts.js

document.getElementById('chatForm').addEventListener('submit', async function(event) {
    event.preventDefault();
    const messageContent = document.getElementById('userMessage').value;
    const sendButton = document.getElementById('sendButton');
    const loadingAnimation = document.getElementById('loadingAnimation');

    // Disable send button and show loading animation
    sendButton.disabled = true;
    loadingAnimation.style.display = 'block';

    try {
        const response = await fetch('chat.php', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ message: messageContent })
        });

        if (!response.ok) {
            throw new Error('Erreur réseau');
        }

        const resultText = await response.text();
        console.log('Réponse brute:', resultText); // Message de débogage

        try {
            const result = JSON.parse(resultText);
            if (result.error) {
                throw new Error(result.error);
            }

            let chatOutput = document.getElementById('chatOutput');
            chatOutput.innerHTML += `<p><strong>User:</strong> ${messageContent}</p>`;
            chatOutput.innerHTML += `<p><strong>Assistant:</strong> ${result.response}</p>`;

            document.getElementById('userMessage').value = '';  // Clear input field

            chatOutput.scrollTop = chatOutput.scrollHeight;  // Scroll to bottom
        } catch (jsonError) {
            console.error('Erreur de parsing JSON:', jsonError);
        }
    } catch (error) {
        console.error('Il y avait un problème avec l\'opération fetch:', error);
        alert('Erreur lors de l\'envoi du message. Veuillez réessayer.');
    } finally {
        // Enable send button and hide loading animation
        sendButton.disabled = false;
        loadingAnimation.style.display = 'none';
    }
});

const themeToggle = document.querySelector('.theme-toggle');
if (themeToggle) {
    themeToggle.addEventListener('click', function() {
        const bodyClassList = document.body.classList;
        const theme = bodyClassList.contains('bg-light') ? 'dark' : 'light';

        if (theme === 'dark') {
            bodyClassList.remove('bg-light');
            bodyClassList.add('bg-dark');
            bodyClassList.remove('text-dark');
            bodyClassList.add('text-white');
        } else {
            bodyClassList.remove('bg-dark');
            bodyClassList.add('bg-light');
            bodyClassList.remove('text-white');
            bodyClassList.add('text-dark');
        }

        const cards = document.querySelectorAll('.card');
        cards.forEach(card => {
            if (theme === 'dark') {
                card.classList.add('bg-dark');
                card.classList.add('text-white');
            } else {
                card.classList.remove('bg-dark');
                card.classList.remove('text-white');
            }
        });
    });
}

// Add animations for better user experience
const userMessageInput = document.getElementById('userMessage');
if (userMessageInput) {
    userMessageInput.addEventListener('focus', function() {
        this.classList.add('input-focus');
    });

    userMessageInput.addEventListener('blur', function() {
        this.classList.remove('input-focus');
    });
}
"

So I need to create a dictionary that records the user messages to place them in the following prompt, is that correct? I thought the "chat" function/API did this automatically.

**Comment by BruceMacD** [comment]
Correct, you'll have to store a dictionary of records in your client-side php code. The server doesn't track any chat state.

Gonna resolve this one for now because we have found the problem. Feel free to ask any follow-up questions though.
