### ISSUE TITLE
Question: Node or browser?

### ISSUE THREAD

**Issue by rahulmehtas** [ollama/ollama-js#127]
Question: Node or browser?

**Comment by BruceMacD** [comment]
Hi @rahulmehtas, if you're using the library in server-side JavaScript (such as Node) use this import:
`import ollama from 'ollama'`

If you're using JavaScript which runs in the browser (such as a basic script) use this import:
`import ollama from 'ollama/browser'`

Hope that helps.

**Comment by sheng-di** [comment]
Thanks for detailed instruction.
