### ISSUE TITLE
Expose type `AbortableAsyncIterator`

### ISSUE THREAD

**Issue by matthiasgeihs** [ollama/ollama-js#152]
Stream-based responses like the one that is returned from the `ollama.chat` call below are of type `AbortableAsyncIterator`.

```
const response = await ollama.chat({ model: 'llama3.1', messages: [message], stream: true });
```

However, the type `AbortableAsyncIterator` is unfortunately not exported, so we cannot use it directly to specify the type of such values (when writing TypeScript).

Would be great if `AbortableAsyncIterator` would be exposed in `index.d.ts`/`browser.d.ts`.

**Comment by hopperelec** [comment]
Looks like a duplicate of https://github.com/ollama/ollama-js/issues/135

**Comment by matthiasgeihs** [comment]
right, closing in favor of #135
