### ISSUE TITLE
ollama.embed is returning different embeddings compared to vanilla Ollama

### ISSUE THREAD

**Issue by eugeniosegala** [ollama/ollama-js#170]
The following request:

```
const response = await ollama.embed({
    model: 'nomic-embed-text:v1.5',
    input: "hello",
  });
```

Is returning very different embeddings:

```
 0.017930806, -0.0058585233,   -0.17534214,   -0.013760389,
```

Compared to vanilla Ollama:

```
curl http://localhost:11434/api/embeddings -d '{
  "model": "nomic-embed-text:v1.5",
  "prompt": "hello"
}'
```

Why?

```
0.42144104838371277, -0.13775105774402618, -4.1203837394714355, -0.3233441710472107
```

Is Ollama JS applying some sort of normalisation?

**Comment by eugeniosegala** [comment]
Thank you @hopperelec.

I will try this.

What is the difference between the 2? I did not notice the `embeddings` function in the doc.

**Comment by hopperelec** [comment]
I believe embeddings is a deprecated version, so generally you should use embed
