### ISSUE TITLE
embeddings method always throws error

### ISSUE THREAD

**Issue by eaton** [ollama/ollama-js#29]
Relatively new to the stack, but the ollama class’s “embeddings” method consistently seems to consistently return a “model required” error whenever it’s called, even when a model that works with other methods is provided.

Making a direct post to the /api/embeddings endpoint with Fetch works fine.

**Comment by eaton** [comment]
Just tracked this one down — #30 fixes it.

**Comment by BruceMacD** [comment]
Thanks for the fix and report. Just released v0.4.4 with the fix.
