### ISSUE TITLE
Chat completion 

### ISSUE THREAD

**Issue by d-strukt** [ollama/ollama-js#34]
How could I use ollama-js as a writing assistant? Similar to openai chat completion:
https://platform.openai.com/docs/guides/text-generation/chat-completions-api

**Comment by BruceMacD** [comment]
Hi @d-strukt that sounds like a scenario for setting the system message. Maybe something like this:
```
import ollama from 'ollama'

const msgs = [
    {"role": "system", "content": "You are a helpful writing assistant."},
    {"role": "user", "content": "The hero of my story just found the magic sword, what happens next?"}
]
const response = await ollama.chat({ model: 'llama2', messages: msgs})
// do something with the response
```

**Comment by kungfooman** [comment]
Actual completion:

```js
const ret = await ollama.generate({
  model: "llama3.1",
  prompt: "Finish simple task, end with exclamation mark:\n1 + 2 =",
  stream: false,
  raw: true,
});
ret.response;
```

Only problem is models write too much crap:

![Image](https://github.com/user-attachments/assets/b25541de-6f13-42e8-a1c0-5b0c11b70acb)
