### ISSUE TITLE
Idiomatic way to cancel request?

### ISSUE THREAD

**Issue by nanmu42** [ollama/ollama-js#39]
Hi, Ollama is great, love it.

I am trying to handle user cancellation during generation, so far I am trying [`AsyncGenerator.prototype.return()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGenerator/return) of the return value of `await ollama.chat` but it freezes the Ollama server and all following requests hang.

I see ollama-js is using `fetch` and normally we use [`AbortController` ](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) to signal abort. Is there something similiar in ollama-js?

Thank you for your effort and time.

**Comment by BruceMacD** [comment]
Hey @nanmu42, I just ran into this too. I've merged a change which is in the new release (`v0.4.6`)

Here's an example of how to use it:
0ebda6ecb9dafd8ac35e54ea1f02adb5a96076d1

**Comment by NateYip** [comment]
> Hey [@nanmu42](https://github.com/nanmu42), I just ran into this too. I've merged a change which is in the new release (`v0.4.6`)
> 
> Here's an example of how to use it: https://github.com/ollama/ollama-js/blob/main/examples/abort/abort.ts

here is new url: https://github.com/ollama/ollama-js/tree/main/examples/abort
