### ISSUE TITLE
Username & password?

### ISSUE THREAD

**Issue by lebrunel** [ollama/ollama-js#41]
This library docs show username and password as options for the push and pull endpoints. The main Ollama API docs don't list those as accepted params, nor the python library, instead the suggestion is you must register with ollama and submit public key from `~/.ollama/id_ed25519.pub`.

Is username/password an accepted auth method of these endpoints? Or this an error in this library?

**Comment by BruceMacD** [comment]
Hi @lebrunel, I added the username/password here since they were in the Ollama push logic, but they look like they were added as a "future idea" and not actually used. Thanks for mentioning this, I'm going to remove them now, you should rely on the pub key that the server will manage.
