### ISSUE TITLE
Do local calls require hardware

### ISSUE THREAD

**Issue by jiangming96** [ollama/ollama-js#53]
Is there a requirement for the graphics memory of the local graphics card when calling the local model through Ollamajs? Can it be used directly without pre training?

**Comment by BruceMacD** [comment]
Hi @jiangming96 this is a client library for the Ollama server and doesn't contain the LLM runtime as of now:
github.com/ollama/ollama

In general though the memory required will vary by the model. You can see some examples in the Ollama repo README linked above. Let me know if you have any more questions.

**Comment by jiangming96** [comment]
Okay, thank you

**Comment by jiangming96** [comment]
> Hi @jiangming96 this is a client library for the Ollama server and doesn't contain the LLM runtime as of now: github.com/ollama/ollama
> 
> In general though the memory required will vary by the model. You can see some examples in the Ollama repo README linked above. Let me know if you have any more questions.

Okay, thank you
