### ISSUE TITLE
New to JS and do not understand how to import it

### ISSUE THREAD

**Issue by RanchMonster** [ollama/ollama-js#65]
I know this Probably not where I should have put this but I am new to using imports in Javascript I use Javascript before but never with imports and I have no dot JS installed i've used that before but I just can't figure out how to import it Correctly i'm trying to run it in a browser 
this is what I have so far I just worte this to test it I also made A version that uses python which is A language I'm much more familiar with but I don't like using Python and web socket to send data back and forth 
import("ollama").then(module => {
const AI = new module.Ollama({"host":"XXXXXXXX"});
const messageList=[]
async function message(){
    const input = document.getElementById('messageInput');
    let message = input.value;
    appendMessage(message)
    messageList.push({"role":"user","content":message});
    const response= await AI.chat({"model":"gemma","messages":messageList,"stream":true})
    for await (const chunk of response) {
        stream(chunk)
        }
}   
async function stream(response){
const messages= document.getElementById('messages');
const current=document.getElementById("current");
const nextContent=response.message.content;
const end=response.done;
if(current==null){
    const temp=document.createElement("li");
    temp.id="current";
    messages.appendChild(temp);
    messageList.push(response.message);
    return stream(response);
}
if(!end){
        current.innerHTML+=nextContent.replace('\n','<br>');
        messageList[messageList.length-1].content+=nextContent;
    
}else{
    current.innerHTML+=nextContent.replace('\n','<br>');
    current.id="";
}
}
function appendMessage(message) {
const messages = document.getElementById('messages');
const li = document.createElement('li');
li.innerHTML = message.replace('\n','<br>');
messages.appendChild(li);
}
}).catch(error => {
    console.error("Error loading module:", error);
});

**Comment by BruceMacD** [comment]
Hi @RanchMonster here is a quick end-to-end example of how to create a project that uses the ollama-js library in the browser. For this example I'll use React.

1. Create a new React project template, in this case I'll name it `hello-world-ollama`.
```
npx create-react-app hello-world-ollama
```
2. Within the created directory (in this case `hello-world-ollama`) run:
```
npm install ollama
```
3. Open `src/App.js`
4. Get started working the Ollama `ollama/browser` library. Here some example code:
```
import React, { useEffect, useState } from 'react';
import ollama from 'ollama/browser';
import './App.css';

function App() {
  const [models, setModels] = useState([]);

  useEffect(() => {
    const fetchModels = async () => {
      const response = await ollama.list();
      console.log(response.models);
      setModels(response.models); // Store fetched models in state
    };

    fetchModels();
  }, []);

  return (
    <div className="App">
      <header className="App-header">
      {models.length > 0 ? (
          <ul>
            {models.map((model, index) => (
              <li key={index}>{model.name}</li> // Example: Assuming each model has a 'name' property
            ))}
          </ul>
        ) : (
          <p>Loading models...</p>
        )}
      </header>
    </div>
  );
}

export default App;
```
5. Start the React app:
```
npm start
```
6. Go to http://localhost:3000/ in your browser

Hope that helps
