### ISSUE TITLE
little ui bug in Mac safari

### ISSUE THREAD

**Issue by kirinrin** [ollama/ollama-js#71]
When I want upload a doc in Knowledge Bases Tab. I found upload button almost has been blocked.
![image](https://github.com/ollama/ollama-js/assets/2627788/67a78818-b2d8-40d0-8ecd-4d01bf196a29)

**Comment by BruceMacD** [comment]
Hi @kirinrin, thanks for the report but your issue appears to be for another project. This is just the Ollama javascript client library project.

Could this be the project you were looking for?
https://github.com/sugarforever/chat-ollama

Let me know if that isn't the case.
