### ISSUE TITLE
Cors errors when using ollama/browser

### ISSUE THREAD

**Issue by POBGit** [ollama/ollama-js#73]
I'm trying to use ollama-js/browser in my application writing in TS. I'm running this app on my computer, with the ollama server and apache. I created a vhost, so I can access my app at this url http://dev.my-app.local/, which points to 127.0.0.1. I bundled my code with webpack.

The problem is that I'm trying to run this simple code, but I have CORS errors (204 error code) : 
```
import {Ollama} from 'ollama/dist/browser.mjs'

async function run() {
    const ollama = new Ollama({host: 'http://localhost:11434'})

    const response = await ollama.generate({
        model: 'mistral',
        prompt: "Why is the sky blue?",
        stream: true
    });

    console.log(response);
}

run();
```

I read in the [official ollama docs](https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server) that I need to set up environment variables `OLLAMA_HOST=*` and `OLLAMA_ORIGINS=*`, but it does not fix my issue.

I then tried with this simpler code, and I don't have CORS errors.
```
const request = fetch(URL, {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json'
    },
    body: JSON.stringify({
        model: 'mistral',
        prompt: "Why is the sky blue?",
    }),
});
```

Any idea?

**Comment by j2l** [comment]
Thanks @POBGit your solution fixed my issue.

**Comment by monotykamary** [comment]
```sh
launchctl setenv OLLAMA_HOST "*"   
launchctl setenv OLLAMA_HOST "0.0.0.0"
```
Running these commands and restarting Ollama seems to work fine on my end on my M2 mac 🤔

**Comment by BruceMacD** [comment]
I believe this should be fixed now with most recent Ollama release, it needed to allow more headers cross-origin. If that isn't the case please let me know.

**Comment by royokello** [comment]
@POBGit what was the solution?

**Comment by mmar58** [comment]
Hi, I found a solution. We can use a node js middle man. Who will receive prompt through the api and send ollama stream response.
I created a node project https://github.com/mmar58/Ollama-Global-API for this reason. You guys can also try it. It allows you to access ollama through any network on any device thought the api.
