### ISSUE TITLE
js 的 demo 运行不起来啊

### ISSUE THREAD

**Issue by chergn** [ollama/ollama-js#75]
<img width="1146" alt="image" src="https://github.com/ollama/ollama-js/assets/43592730/91c2ae29-5156-4f73-93eb-cfdae35cf870">

**Comment by m0o0scar** [comment]
Your file name in command line is incorrect. Your file name is `ollama.js`, while you've typed `alama.js` in terminal 😑

**Comment by BruceMacD** [comment]
Hi, @chergn as m0o0scar pointed out it looks like you have a typo in your file name. Let me know if that is not the case 👍

**Comment by elarbor** [comment]
> Your file name in command line is incorrect. Your file name is `ollama.js`, while you've typed `alama.js` in terminal 😑

![Image](https://github.com/user-attachments/assets/9ab819b4-3c4b-475f-a3b7-77804955dd33)

**Comment by BruceMacD** [comment]
@elarbor Make sure ollama is running locally. Looks like the server is not accessible.

**Comment by elarbor** [comment]
> [@elarbor](https://github.com/elarbor) Make sure ollama is running locally. Looks like the server is not accessible.

我安装[ollama](https://ollama.com/download)了
![Image](https://github.com/user-attachments/assets/0e9deff0-1c36-4189-b022-bd6b1474bad9)

是需要再安装大模型吗？
