### ISSUE TITLE
CORS issue on firefox browsers

### ISSUE THREAD

**Issue by mrdjohnson** [ollama/ollama-js#80]
When using ollama/browser and trying to pull models or show information my users get CORS issues. I have replicated this issue on firefox browsers. I am able to load models initially because I am calling it manually, but when getting the same list of models through ollamajs they run into CORS issues. 

I am not sure what is going on but it is strange that a manual fetch works (in my case) but a fetch through the library does not

any advisement would be helpful!

**Comment by BruceMacD** [comment]
Hi @mrdjohnson, are there any specific errors in the browser console logs? That could help with debugging, we had some CORS changes recently so this could have effected this.

**Comment by mrdjohnson** [comment]
<img width="676" alt="image" src="https://github.com/ollama/ollama-js/assets/6767910/cc09bab5-2841-4fb3-a059-9c7259cd9e4a">

**Comment by mrdjohnson** [comment]
<img width="1210" alt="image" src="https://github.com/ollama/ollama-js/assets/6767910/93d0ec78-9b90-4bc6-a915-a4b9634880be">

**Comment by BruceMacD** [comment]
Thanks for the update @mrdjohnson, I was able to reproduce this. I have a change up (#4086) that will fix the issue.

**Comment by mrdjohnson** [comment]
Looking forward to the change!! 

are those config options modifiable by the user? or do i need to wait for this PR to be merged?

**Comment by BruceMacD** [comment]
@mrdjohnson this change is going to need the PR to be merged

**Comment by mrdjohnson** [comment]
@BruceMacD  Congrats on the merge!

Will this be fixed automatically when the next version of ollama comes out?

**Comment by BruceMacD** [comment]
It should be, just needs an ollama version update when the next release it out.

**Comment by mrdjohnson** [comment]
Okay! I'm still a little lost on how calling the api manually works, but calling it through ollamajs did not work, but looking forward to the change!
