### ISSUE TITLE
ReferenceError: XMLHttpRequest is not defined

### ISSUE THREAD

**Issue by liugezhou** [ollama/ollama-js#84]
<img width="593" alt="image" src="https://github.com/ollama/ollama-js/assets/29797703/27ba083e-2862-4f31-a8ff-99ce3649e04e">

When i run node demo.js,and then:

 /User/xxx/Demo/aidemo/node_modules/whatwg-fetch/dist/fetch.umd.js:540
      var xhr = new XMLHttpRequest();
                ^

ReferenceError: XMLHttpRequest is not defined

**Comment by ozgrozer** [comment]
I had the same error on Node.js v17. Tried lots of things then accidently found out that it's working perfect with Node.js v18.

**Comment by skeetmtp** [comment]
Note for people stuck to nodejs < 18
```bash
npm install xhr2
```

```js
global.XMLHttpRequest = require('xhr2');
```

**Comment by stephcurt** [comment]
> Note for people stuck to nodejs < 18
> 
> ```shell
> npm install xhr2
> ```
> 
> ```js
> global.XMLHttpRequest = require('xhr2');
> ```

This worked for me, although as soon as I fixed it I realized I'd set that dockerfile to node14 for some reason (smh).

**Comment by cool-firer** [comment]
is the supposed to be fixed?  xhr2 global patch is not convenient
